# **SIN 393 – Introduction to Computer Vision (2023)**

# Prova 01 

Prof. João Fernando Mari ([*joaofmari.github.io*](https://joaofmari.github.io/))

---

In [18]:
import numpy as np
from sklearn import metrics
from scipy import spatial
import matplotlib.pyplot as plt


## Exercício 1

In [2]:
X = np.array([[2, 6],
              [4, 2],
              [6, 2],
              [2, 3],
              [1, 7],
              [8, 4],
              [1, 4],
              [4, 8],
              [9, 3]])

y = np.array([2, 0, 1, 0, 2, 1, 0, 2, 1])

X_test = np.array([[2, 6],
                   [2, 4],
                   [6, 3]])

In [3]:
d_mat = spatial.distance_matrix(X_test, X)

In [17]:
np.set_printoptions(precision=4)

print(d_mat)

[[0.     4.4721 5.6569 3.     1.4142 6.3246 2.2361 2.8284 7.6158]
 [2.     2.8284 4.4721 1.     3.1623 6.     1.     4.4721 7.0711]
 [5.     2.2361 1.     4.     6.4031 2.2361 5.099  5.3852 3.    ]]


In [ ]:
# plt.plot(

## Exercício 2

In [5]:
pred = np.array([0, 1, 2, 0, 1, 1, 1, 1, 1, 2, 2, 2])
true = np.array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])

In [6]:
cm = metrics.confusion_matrix(true, pred)
report = metrics.classification_report(true, pred)

In [7]:
print(cm)

[[2 1 1]
 [0 4 0]
 [0 1 3]]


In [8]:
print(report)

              precision    recall  f1-score   support

           0       1.00      0.50      0.67         4
           1       0.67      1.00      0.80         4
           2       0.75      0.75      0.75         4

    accuracy                           0.75        12
   macro avg       0.81      0.75      0.74        12
weighted avg       0.81      0.75      0.74        12



## Exercício 3

In [9]:
W0 = np.array([[0.3, 0.1, 0.2],
               [0.1, 0.2, 0.4]])

b0 = np.array([0.5, 0.2, 0.7])

W1 = np.array([[0.4, 0.1], 
               [0.2, 0.3],
               [0.5, 0.6]])
b1 = np.array([0.1, 0.3])

In [10]:
x = np.array([0.8, 0.3])
y = np.array([1.0, 0.0]) 

In [11]:
v0 = np.dot(x, W0) + b0
print(v0)

[0.77 0.34 0.98]


In [12]:
y0 = np.maximum(v0, 0)
print(y0)

[0.77 0.34 0.98]


In [13]:
v1 = np.dot(y0, W1) + b1
print(v1)

[0.966 1.067]


In [14]:
y_ = np.exp(v1)
y1 = y_ / y_.sum()
print(y1)

[0.4748 0.5252]


In [15]:
y1.sum()

1.0

In [16]:
e_ = y * np.log(y1)
e = -e_.sum()
print(e)

0.7449217639469883
