# **SIN 393 – Introduction to Computer Vision (2023)**

# Lecture 05 - Part 2b - Deep Learning

Prof. João Fernando Mari ([*joaofmari.github.io*](https://joaofmari.github.io/))

---
* Implementation of the same model in Part 2, but in PyTorch.

## Importing the required libraries

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable

import graphviz
from graphviz import Digraph

## Model
---

In [2]:
class Net(nn.Module):

    def __init__(self):
        super().__init__()

        self.linear0 = nn.Linear(1, 2)
        self.linear1 = nn.Linear(2, 1)

    def forward(self, x):
        x = self.linear0(x)
        x = F.sigmoid(x)

        x = self.linear1(x)
        x = F.sigmoid(x)

        return x

In [3]:
# Instância um objeto da classe Net
model = Net()
print(model)

Net(
  (linear0): Linear(in_features=1, out_features=2, bias=True)
  (linear1): Linear(in_features=2, out_features=1, bias=True)
)


![title](figures/nn02_ok.png)

### Loss and optimizer

In [4]:
# Função de perda (loss) 
criterion = nn.MSELoss(reduction='mean')
### criterion = nn.CrossEntropyLoss()
### criterion = nn.NLLLoss()

# Otimizador - Stochastic Gradient Descent
optimizer = optim.SGD(model.parameters(), lr=0.01)

### Inputs and outputs

In [5]:
x = torch.FloatTensor([0.3])
y = torch.Tensor([1.0])

print(x.shape, y.shape)

torch.Size([1]) torch.Size([1])


### Weights and bias

In [6]:
state_dict = model.state_dict()
state_dict['linear0.weight'] = torch.tensor([[0.1],
                                             [0.2]])
state_dict['linear0.bias'] = torch.tensor([0.25, 0.25])
state_dict['linear1.weight'] = torch.tensor([[0.5, 0.6]])
state_dict['linear1.bias'] = torch.tensor([0.35])

model.load_state_dict(state_dict)

<All keys matched successfully>

In [7]:
print('\n>> Weights and bias - Iteration 0')
for k, v in model.named_parameters():
    print('\n', k, v)


>> Weights and bias - Iteration 0

 linear0.weight Parameter containing:
tensor([[0.1000],
        [0.2000]], requires_grad=True)

 linear0.bias Parameter containing:
tensor([0.2500, 0.2500], requires_grad=True)

 linear1.weight Parameter containing:
tensor([[0.5000, 0.6000]], requires_grad=True)

 linear1.bias Parameter containing:
tensor([0.3500], requires_grad=True)


## Forward pass
---

In [8]:
model.zero_grad()

output = model(Variable(x))
print('\n>> Forward:')
print(output)

loss = criterion(output, Variable(y))
print('\n>> Loss:')
print(loss)


>> Forward:
tensor([0.7273], grad_fn=<SigmoidBackward0>)

>> Loss:
tensor(0.0744, grad_fn=<MseLossBackward0>)


In [9]:
print('\n>> Gradients 0')
print('\nLayer 1')
print(model.linear1.weight.grad)
print(model.linear1.bias.grad)
print('\nLayer 0')
print(model.linear0.weight.grad)
print(model.linear0.bias.grad)


>> Gradients 0

Layer 1
None
None

Layer 0
None
None


## Backpropagation pass
---

In [10]:
loss.backward()

print('\n>> Gradients 1')
print('\nLayer 1')
print(model.linear1.weight.grad)
print(model.linear1.bias.grad)
print('\nLayer 0')
print(model.linear0.weight.grad)
print(model.linear0.bias.grad)


>> Gradients 1

Layer 1
tensor([[-0.0616, -0.0624]])
tensor([-0.1082])

Layer 0
tensor([[-0.0040],
        [-0.0048]])
tensor([-0.0133, -0.0158])


## Gradient descent
---

In [11]:
optimizer.step()

print('\n>> Weights and bias - Iteration 1')
for k, v in model.named_parameters():
    print('\n', k, v)


>> Weights and bias - Iteration 1

 linear0.weight Parameter containing:
tensor([[0.1000],
        [0.2000]], requires_grad=True)

 linear0.bias Parameter containing:
tensor([0.2501, 0.2502], requires_grad=True)

 linear1.weight Parameter containing:
tensor([[0.5006, 0.6006]], requires_grad=True)

 linear1.bias Parameter containing:
tensor([0.3511], requires_grad=True)


## Bibliography
---
* Rabindra Lamsal. A step by step forward pass and backpropagation example
    * https://theneuralblog.com/forward-pass-backpropagation-example/
* Matt Mazur. A Step by Step Backpropagation Example
    * https://mattmazur.com/2015/03/17/a-step-by-step-backpropagation-example/
* Soumith Chintala. DEEP LEARNING WITH PYTORCH: A 60 MINUTE BLITZ.
    * https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html 
* A GENTLE INTRODUCTION TO TORCH.AUTOGRAD
    * https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html 
* Rabindra Lamsal. A step by step forward pass and backpropagation example
    * https://theneuralblog.com/forward-pass-backpropagation-example/
* Matt Mazur. A Step by Step Backpropagation Example
    * https://mattmazur.com/2015/03/17/a-step-by-step-backpropagation-example/